### ISSUE TITLE
SideCar keeps Restarting, as Service or Forground Process

### ISSUE THREAD

**Issue by BaddMann** [Graylog2/collector-sidecar#120] opened 2016-12-22 21:46 UTC
### Problem description
Setting up Sidecar with FileBeats on my Ubuntu 12.04 VM image.
it's providing logs just great, but it's also causing a lot of logs.
Every minute this happens, sometimes faster:

>  Dec 22 13:13:17 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:17-07:00" level=info msg="[filebeat] Starting (exec driver)" 
> Dec 22 13:13:27 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:27-07:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file." 
> Dec 22 13:13:27 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:27-07:00" level=info msg="[filebeat] Stopping" 
> Dec 22 13:13:29 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:29-07:00" level=info msg="[filebeat] Starting (exec driver)" 
> Dec 22 13:13:39 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:39-07:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file." 
> Dec 22 13:13:39 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:39-07:00" level=info msg="[filebeat] Stopping" 
> Dec 22 13:13:41 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:41-07:00" level=info msg="[filebeat] Starting (exec driver)" 
> Dec 22 13:13:51 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:51-07:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file." 
> Dec 22 13:13:51 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:51-07:00" level=info msg="[filebeat] Stopping" 
> Dec 22 13:13:53 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:13:53-07:00" level=info msg="[filebeat] Starting (exec driver)" 
> Dec 22 13:14:03 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:14:03-07:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file." 
> Dec 22 13:14:03 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:14:03-07:00" level=info msg="[filebeat] Stopping" 
> Dec 22 13:14:05 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:14:05-07:00" level=info msg="[filebeat] Starting (exec driver)" 
> Dec 22 13:14:15 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:14:15-07:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file." 
> Dec 22 13:14:15 nebula /usr/bin/graylog-collector-sidecar[17991]: time="2016-12-22T13:14:15-07:00" level=info msg="[filebeat] Stopping"

### Steps to reproduce the problem

Maybe Tags?
I have three tags defined on sidecar, but have not defined two of them in Graylog2 yet. Maybe that's a cause?
Will remove them to verify.

### Environment

* Sidecar Version: collector-sidecar_0.1.0-1_amd64.deb
* Graylog Version: Graylog 2.1.2+50e449a 
* Operating System: Ubuntu 12.04
* Elasticsearch Version: latest Docker Image
* MongoDB Version: latest Docker Image

**Comment by mariussturm** [comment] 2016-12-23 11:01
Duplicate of #116, please follow that issue. Thanks!

**Closed by mariussturm** 2016-12-23 11:01 UTC

**Comment by mariussturm** [comment] 2017-01-11 10:10
This should be fixed in 0.1.0-beta.3, please test again.
