### ISSUE TITLE
node_name is not set to hostname as documented

### ISSUE THREAD

**Issue by meatzie** [Graylog2/collector-sidecar#368] opened 2019-06-06 13:17 UTC
### Problem description
On install of latest release, node-name is defaulting to "graylog-sidecar" instead of the hostname as documented.

### Steps to reproduce the problem

1. Install graylog sidecar from elevated command prompt using the following command:
`graylog_sidecar_installer.exe /S -SERVERURL=https://graylog.domain.com:9000/api -APITOKEN=******`
2. Check "C:\Program Files\Graylog\sidecar\sidecar.yml"
3. Relevant configuration section reads:

`# The node name of the sidecar. If this is empty, the sidecar will use the`
`# hostname of the host it is running on.`
`# Default: ""`
`node_name: "graylog-sidecar"`

### Environment

* Sidecar Version: 1.0.1-1
* Graylog Version: 3.0.2+1686930, codename Space Moose
* Operating System: Windows Server 2012 R2
* Elasticsearch Version: 6.8.0
* MongoDB Version: v3.6.12

**Comment by mpfz0r** [comment] 2019-06-06 13:32
Duplicate of #339 
We just did not backport this into 1.0 yet

**Closed by mpfz0r** 2019-06-06 13:32 UTC

**Comment by han911976** [comment] 2019-06-25 07:24
Sorry for commenting on closed issue
but seems the problem is not yet fixed on 1.0.1
faced the above problem while using the same command.

**Comment by mpfz0r** [comment] 2019-07-03 07:01
@han911976 sorry if I was unclear. I meant that it is not backported into the 1.0 branch yet.
I might consider building a 1.0.2 release with this fix.

**Comment by han911976** [comment] 2019-07-04 04:13
@mpfz0r nvm Thanks for the reply!
I have written a batch script to comment out the line
It is still solvable by some efforts xd
