### ISSUE TITLE
Sidecar collector errors for Windows Server 2008 R2

### ISSUE THREAD

**Issue by mgsteiner** [Graylog2/collector-sidecar#172] opened 2017-05-10 11:55 UTC
### Problem description
When the windows service starts I start to get the following entries in the collector log.
The yml config file is the same as in other windows servers 2016 where the collector is working fine and there is no errors.

level=error msg="[RequestConfiguration] Bad response status from Graylog server: 403 Forbidden" 
time="2017-05-10T13:46:41+02:00" level=error msg="Can't fetch configuration from Graylog API: invalid character '<' looking for beginning of value" 

Any hint?

### Steps to reproduce the problem

Nothing in particular, just install the collector and configure the yml file. Same as for Windows Server 2016 (which is working fine)

### Environment

* Sidecar Version: 0.1.1
* Graylog Version: 2.2.3
* Operating System: Windows Server 2008 R2
* Elasticsearch Version: 2-4
* MongoDB Version: 3.x

**Comment by mariussturm** [comment] 2017-05-10 12:02
We don't support Windows Server 2008 because it has some incompatibilities we don't want work around. But in your case it looks like a configuration issue, maybe double checking the `server_url` could fix it already?

**Comment by mgsteiner** [comment] 2017-05-10 13:05
Thanks for the reply.
When you say Windows Server 2008 that is also including the R2?

No the server_url is the standard format as in the implementation guide and it is working fine for windows server 2016 --> http://<graylog-server>:9000/api

We have just tried in another 2008 server and also we got the same problem.
Any idea how we can workaround this in order to get the logs to Graylog server?

**Comment by mariussturm** [comment] 2017-05-10 14:15
Ah sorry confused that with Windows 2003, that's the one that doesn't work with the Graylog Sidecar.
Could append the Graylog server logs at the time a request is made by the Sidecar?

**Comment by jgibbarduk** [comment] 2017-05-11 08:15
I have the same issue on Windows 10 64bit.

**Comment by mariussturm** [comment] 2017-05-11 09:26
@jgibbarduk please provide some server and sidecar logs, I can't guess the solution from the given informations.

**Comment by jgibbarduk** [comment] 2017-05-11 11:15
Hi @mariussturm 

I've been on the IRC channel talking to joschi.

Problem Summary: 
I've installed the Graylogs VM template on ESXi and have the server working, but when I try to communicate with the server using sidecar, I get a 403 error before it pulls down and config.

I'd initially only tried sending logs from sidecar on Windows 10 64bit, but have just tried from a CentOS box and I'm getting the same failures. Details below...

Server Details:
- Graylog VM (graylog-2.2.3-1.ova) template used to create VM on VMWare ESXi 5.5.0 host 
- Server up and running with DHCP IP assigned, web UI accessible
- No errors on server (system -> logging)
- SSH working OK
- Can access http:<ip>:9000/api OK using REST client on same machine as sidecar

Windows 10 64bit Details:
- Sidecar version: Graylog Collector Sidecar version 0.1.1 (0f49c46) [go1.7.4/amd64]
- Sidecar config:  https://pastebin.com/vSBQfH85
- Sidecar logs: https://pastebin.com/i8Pt65Fq

CentOS 64bit Details:
- Sidecar version: Graylog Collector Sidecar version 0.1.1 (0f49c46) [go1.7.4/amd64]
- Sidecar config: https://pastebin.com/440eFYpA
- Sidecar logs: https://pastebin.com/p0JdQYHJ

**Comment by mariussturm** [comment] 2017-05-22 10:41
Sorry I can not reproduce your issue. I tried with exactly the same versions and the connection worked perfectly fine for me. In the Sidecar los it says that it's forbidden to access the Graylog API on port 9000. Is there some proxy or firewall in between? Maybe soemthing else is blocking the registraton request?
Could you try to call the API manually with:
```
curl -v -u admin:password http://10.101.104.236:9000/api/plugins/org.graylog.plugins.collector/collectors
```

**Comment by mgsteiner** [comment] 2017-05-23 07:54
I tried now with my server URL http://<server>:9000/api and this is what I got:

*   Trying xxx.xxx.xxx.xxx
* TCP_NODELAY set
* Connected to kdc-httpproxy.kncorp.group.local (xxx.xxx.xxx.xxx) port 8080 (#0)
* Server auth using Basic with user '<adm-user>'
> GET http://<graylogserver>/api HTTP/1.1
> Host: <graylogserver>:9000
> Authorization: Basic YWRtLXN0ZWluZXJtOlN1cGVyNDIk
> User-Agent: curl/7.54.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 403 Forbidden
< Connection: close
< Content-Type: text/html; charset=UTF-8
< Cache-Control: no-cache
< Date: Tue, 23 May 2017 06:59:08 

If i understand correctly the connection is Forbidden, but I was checking the with the networking guys and the firewall as the same rules for all windows server no matter which version.

Do you have any advice regarding security things or differences to check when installing Graylog on different windows server versions?

**Comment by jgibbarduk** [comment] 2017-05-23 08:00
I also get:
> < HTTP/1.1 403 Forbidden
> < Date: Mon, 22 May 2017 19:01:54 GMT
> < Cache-Control: no-cache
> < Pragma: no-cache
> < Content-Type: text/html; charset="UTF-8"
> < Content-Length: 25370
> < Accept-Ranges: none
> < Via: HTTP/1.1 sophos.http.proxy:8080

It would seem I am getting blocker by my company's internal firewall. It says I can't access a site specified by an IP address. Its odd, as I my other tests to connect to the greylog server have all been successful via the IP address in a browser.

I will associate a DNS name with the server, and see if I can get a connection that way.

Thanks for your help.

**Comment by mariussturm** [comment] 2017-05-23 08:22
@mgsteiner sorry, can't help with general advice because it's highly depended on the proxy software your company is using. This is something your network admins should be able to solve.
Closing this for now till it's not an issue with the sidecar itself.

**Closed by mariussturm** 2017-05-23 08:22 UTC
Labels: to-verify, triaged
