### ISSUE TITLE
Add Ability to Write Arbitrary Config Files

### ISSUE THREAD

**Issue by ReK42** [Graylog2/collector-sidecar#379] opened 2019-09-19 01:33 UTC
### Problem description
Other programs can be used to control the logging input flow however the sidecar cannot manage any configuration files unless it can start the binary itself and specify the path to the configuration within the command.

As an example, I have a "collector" VM that can be placed in a remote location. Devices at that location syslog to the VM, which is received by rsyslog and has retention controlled by logrotate. I then use nxlog to read from those files and send to Graylog, which is controlled by the sidecar. Being able to control the config files for rsyslog (/etc/rsyslog.d/foo.conf) and logrotate (/etc/logrotate.d/foo) through the sidecar would be a great feature. It would require being able to write a config file to an arbitrary location, and being able to execute a command when the file is updated if necessary (e.g. systemctl restart rsyslog).

### Steps to reproduce the problem
N/A

### Environment

* Sidecar Version: 1.0.2
* Graylog Version: 3.1.2
* Operating System: Ubuntu 18.04.3 LTS
* Elasticsearch Version: 6.8
* MongoDB Version: 4.0

**Comment by kroepke** [comment] 2019-09-23 09:36
Hi!

The issue is that we would very much like to avoid writing files at arbitrary locations on a host for security/safety reasons.
In these circumstances we recommend configuring rsyslog to read its configuration from sidecar writable directories.

While we understand the convenience of this, I don't want to imagine the can of worms if we supported writing arbitrary files on the host systems.

Thus I'll be closing this issue for the time being.

Best regards,
Kay

**Closed by kroepke** 2019-09-23 09:36 UTC
