### ISSUE TITLE
Why I cannot config graylog-collector-sidecar which I see in system/Collectors 

### ISSUE THREAD

**Issue by appop** [Graylog2/collector-sidecar#34] opened 2016-06-28 09:03 UTC
When I start collector-sidecar on my vm whcih want to input log,
I see it auto connect to graylog but I cannot config it,

If I need click configurations,and then click on create configuration ?
If I do this but I got a 400 error.

**Comment by mariussturm** [comment] 2016-06-28 09:08
Which Graylog version are you using? And do you get any errors in the server log file?

**Comment by mariussturm** [comment] 2016-07-04 13:52
Closing this for now, feel free to re-open when you got more informations.

**Closed by mariussturm** 2016-07-04 13:52 UTC

**Comment by jesperweiland** [comment] 2016-07-27 15:20
I think I see this issue as well. I'm running Collector 1.1.0-beta.1 and 2.1.0-beta.1. The older versions didn't work either, so I tried upgrading to this beta versions.

I see my collector in the Graylog interface, I click 'manage configurations', I click 'create configuration' and nothing happens.

I get this error in Firebug:

`Unhandled rejection _updateTypeahead@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:116556:1
componentDidMount@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:116530:6
__vendor</</<.notifyAll@https://logging.clientname.eu/vendor.js:14:8592
__vendor</f.close@https://logging.clientname.eu/vendor.js:404:17830
__vendor</</r.closeAll@https://logging.clientname.eu/vendor.js:13:26263
__vendor</</r.perform@https://logging.clientname.eu/vendor.js:13:25605
__vendor</</r.perform@https://logging.clientname.eu/vendor.js:13:25525
__vendor</</<.perform@https://logging.clientname.eu/vendor.js:12:20842
__vendor</</L@https://logging.clientname.eu/vendor.js:12:21025
__vendor</</o.measure/i@https://logging.clientname.eu/vendor.js:12:18756
__vendor</</r.closeAll@https://logging.clientname.eu/vendor.js:13:26263
__vendor</</r.perform@https://logging.clientname.eu/vendor.js:13:25605
__vendor</p.batchedUpdates@https://logging.clientname.eu/vendor.js:398:21537
c@https://logging.clientname.eu/vendor.js:12:19932
o@https://logging.clientname.eu/vendor.js:14:15469
__vendor</</p.enqueueSetState@https://logging.clientname.eu/vendor.js:14:17693
__vendor</</o.prototype.setState@https://logging.clientname.eu/vendor.js:398:15194
__vendor</e.exports.listen/n@https://logging.clientname.eu/vendor.js:415:10651
__vendor</r.prototype.emit@https://logging.clientname.eu/vendor.js:409:1997
__vendor</e.exports.trigger@https://logging.clientname.eu/vendor.js:415:11517
list/promise<@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:119039:1
tryCatcher@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:23285:17
[23]</module.exports/Promise.prototype._settlePromiseFromHandler@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:21391:14
[23]</module.exports/Promise.prototype._settlePromiseAt@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:21465:14
[23]</module.exports/Promise.prototype._settlePromises@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:21581:10
[2]</Async.prototype._drainQueue@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:18871:14
[2]</Async.prototype._drainQueues@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:18881:6
Async/this.drainQueues@https://logging.clientname.eu/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.5875d91e1a331627faf4.js:18763:10
`

I've built the graylog-collector-sidecar by hand (succesfully) because the downloads do not contain the .jar file as described in the documentation. I might need to make a separate issue for that as well.

**Comment by mariussturm** [comment] 2016-07-27 15:48
Thanks for the report!
When I start a fresh OVA with version 2.1.0-beta.1 I can not reproduce this issue. The dialog works as expected. Maybe there is some old or broken data in MongoDB? Could you provide a dump of the collectors and collector_configuration collection?

E.g. on the OVA you can create them with:
```
  /opt/graylog/mongodb/bin/mongodump --db graylog --collection collectors
  /opt/graylog/mongodb/bin/mongodump --db graylog --collection collector_configuration
```

Then compress the whole `dump` directory.

**Comment by mariussturm** [comment] 2016-07-27 16:16
Could you please also provide the OS and Firefox version you are using?

**Comment by jesperweiland** [comment] 2016-07-28 07:01
Using the OVA was a pretty good insight; I just booted the beta OVA and copied the .jar files from there and now it works. It looks like my build was broken somehow.

Thanks a lot for your response 👍
