### ISSUE TITLE
Remote configuration of the collector-sidecar

### ISSUE THREAD

**Issue by tstaals** [Graylog2/collector-sidecar#190] opened 2017-09-21 08:46 UTC
It would be very nice and handy, if you could change the configuration of the collector-sidecar from the graylog web interface once the collector is installed and running.

You could then change for example the tags without the need to login on every collecoter instance and change it manaully.

**Comment by mariussturm** [comment] 2017-09-21 13:34
Duplicate of https://github.com/Graylog2/collector-sidecar/issues/162

**Closed by mariussturm** 2017-09-21 13:34 UTC
Labels: feature, triaged
