### ISSUE TITLE
Graylog service failing after update

### ISSUE THREAD

**Issue by ElZeeBee** [Graylog2/collector-sidecar#188] opened 2017-08-25 17:45 UTC
### Problem description
The Graylog service is failing after updating to version 2.3.1. `journalctl` suggests the failure may be related to Collector Sidecar.

```Aug 25 13:18:45 centos7vm.localdomain systemd[1]: graylog-server.service holdoff time over, scheduling restart.
Aug 25 13:18:45 centos7vm.localdomain systemd[1]: Started Graylog server.
Aug 25 13:18:45 centos7vm.localdomain systemd[1]: Starting Graylog server...
Aug 25 13:18:47 centos7vm.localdomain systemd[1]: graylog-server.service: main process exited, code=exited, status=1/FAILURE
Aug 25 13:18:47 centos7vm.localdomain systemd[1]: Unit graylog-server.service entered failed state.
Aug 25 13:18:47 centos7vm.localdomain systemd[1]: graylog-server.service failed.
Aug 25 13:18:49 centos7vm.localdomain graylog-collector-sidecar[6158]: time="2017-08-25T13:18:49-04:00" level=error msg="[RequestConfiguration] Fetching configuration failed: Get http://127.0.0.1:9000/api/plugins/org.graylog.plugins.collector/5d311f6a-c554-43f5-b0eb-817a5b5a92bc?tags=%5B%22linux%22%2C%22apache%22%2C%22itos%22%5D: dial tcp 127.0.0.1:9000: getsockopt: connection refused"
Aug 25 13:18:50 centos7vm.localdomain graylog-collector-sidecar[6158]: time="2017-08-25T13:18:50-04:00" level=error msg="[UpdateRegistration] Failed to report collector status to server: Put http://127.0.0.1:9000/api/plugins/org.graylog.plugins.collector/collectors/5d311f6a-c554-43f5-b0eb-817a5b5a92bc: dial tcp 127.0.0.1:9000: getsockopt: connection refused"
```

Also posted to Graylog2/graylog2-server#4112

### Steps to reproduce the problem

1. Update Graylog to version 2.3.1 via yum
2. Attempt to access web console
3. Check service status
4. Observe failure

### Environment

* Sidecar Version: 0.1.4
* Filebeat Version: 5.5.1
* Graylog Version: 2.3.1
* Operating System: CentOS 7.3.1611
* Elasticsearch Version: 5.5.2-1
* MongoDB Version: 3.4.7-1

**Comment by joschi** [comment] 2017-08-26 09:23
Duplicate of Graylog2/graylog2-server#4112

**Closed by joschi** 2017-08-26 09:23 UTC
