### ISSUE TITLE
Sidecar 1.4.0 with filebeat doesn’t change path.data & path.logs

### ISSUE THREAD

**Issue by zyxep** [Graylog2/collector-sidecar#475] opened 2023-08-01 12:22 UTC
### Problem description
On linux, the runtime doesn't change `path.data` & `path.logs` based on the config settings in the filebeat configuration. 
You need different path.data & path.logs directories for the runtime to work when using the tags system, but seems like `path.data` & `path.logs` are "hardcoded" some where and therefor doesn't get the directory listed in filebeat's config.

### Steps to reproduce the problem

default config for filebeat:
![Screenshot 2023-08-01 at 2 12 20 PM](https://github.com/Graylog2/collector-sidecar/assets/1403731/a4a4ed89-ceae-400b-8e3a-090fed0bd152)

the systemd service starts filebeat with:
`/usr/share/filebeat/bin/filebeat --path.home /usr/share/filebeat --path.config /etc/filebeat --path.data /var/lib/filebeat --path.logs /var/log/filebeat -c /var/lib/graylog-sidecar/generated/648a0c4345c6352ac3bc9698/filebeat.conf`

### Environment

* Sidecar Version: 1.4.0
* Graylog Version: 5.1.2
* Operating System: Ubuntu 20.04
* Elasticsearch Version: Opensearch 2.x
* MongoDB Version: 6.0.6

**Comment by zyxep** [comment] 2023-08-01 18:59
ya, seems like there is a good chance for it.

**Comment by bernd** [comment] 2023-08-07 14:14
Duplicate of https://github.com/Graylog2/graylog2-server/issues/14228.

**Closed by bernd** 2023-08-07 14:14 UTC
