### ISSUE TITLE
Windows service doesn't reconnect after reboot

### ISSUE THREAD

**Issue by jlad00** [Graylog2/collector-sidecar#185] opened 2017-08-10 19:23 UTC
### Problem description

I have a very similar issue to that of the one described in the closed thread linked below. However, our environment is on a later version of both the sidecar collector and Graylog. This is happening across all Windows servers with the sidecar installed and running.  The nxlog service was uninstalled at the time of the collector installation per the config instructions.

If I restart the sidecar collector service manually, it functions again.

https://github.com/Graylog2/collector-sidecar/issues/142

Log at the time of reboot:
> time="2017-08-10T05:15:43-07:00" level=info msg="Stopping signal distributor" 
time="2017-08-10T05:15:43-07:00" level=info msg="[nxlog] Stopping" 
time="2017-08-10T05:15:43-07:00" level=error msg="[nxlog] Failed to connect to service manager: A system shutdown is in progress." 
time="2017-08-10T05:17:08-07:00" level=info msg="Starting signal distributor" 
time="2017-08-10T05:17:08-07:00" level=info msg="[nxlog] Stopping" 
time="2017-08-10T05:17:09-07:00" level=error msg="[nxlog] Could not send stop control: The service has not been started." 
time="2017-08-10T05:17:19-07:00" level=info msg="[nxlog] Configuration change detected, rewriting configuration file." 
time="2017-08-10T05:17:29-07:00" level=info msg="[nxlog] Starting (svc driver)" 
time="2017-08-10T05:17:29-07:00" level=info msg="[nxlog] Stopping" 
time="2017-08-10T05:17:29-07:00" level=error msg="[nxlog] Could not send stop control: The requested control is not valid for this service." 
time="2017-08-10T05:17:29-07:00" level=info msg="[nxlog] Starting (svc driver)" 
time="2017-08-10T05:17:30-07:00" level=error msg="[nxlog] Could not start service: An instance of the service is already running." 

### Steps to reproduce the problem

1. Reboot the server.

### Environment

* Sidecar Version: 0.1.3
* Graylog Version: 2.2.3
* Operating System: Windows Server 2012 R2
* Elasticsearch Version:
* MongoDB Version:

**Comment by mariussturm** [comment] 2017-08-15 12:34
Hi,
sorry I couldn't reproduce this. Could you try to provide some more system informations like a process list and a list of registered/running services?

**Comment by jtkkex** [comment] 2017-09-07 17:39
I have had a similar problem.  The graylog-collector sidecar needs to be started with "automatic delayed start".  Otherwise it starts too quickly, before all system services are definitely up and running.  Starting nxlog to gather events before the services is up fails and it gives up trying before everything is up.

**Comment by jalogisch** [comment] 2017-10-02 09:56
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by jalogisch** 2017-10-02 09:56 UTC
Labels: to-verify
