### ISSUE TITLE
Authentication (or authorisation) mechanism for collector host to Graylog server.

### ISSUE THREAD

**Issue by anmolsharmaa** [Graylog2/collector-sidecar#264] opened 2018-07-16 15:36 UTC
### Problem description -- (concern)
Lack of a basic authentication mechanism for/from Collector Sidecar before registering (or authorizing) the host to Graylog server for sending logs.   

On installing & running the collector sidecar service by configuring Graylog server API in it, it will automatically register the host, pull file beat configuration and start sending the logs. Without lack of proper authentication in host registration, anyone can overwhelm (DOS|DDOS) the Graylog server with logs and bring the system down.
Please let me know if there is any mechanism currently available for described use case. And if not there please include this in pipeline and get this implemented ASAP. 

### Environment

* Sidecar Version: 0.1.6
* Graylog Version: 2.4.5
* Operating System: CentOS (6|7) 
* Elasticsearch Version: 5.6.10
* MongoDB Version: 3.6.5

**Comment by joschi** [comment] 2018-07-16 15:53
Duplicate of #141

**Comment by anmolsharmaa** [comment] 2018-07-16 16:17
@joschi 
I have already secured the communication between collector and Graylog by enabling SSL. My primary concern was with the collector host registration process. 
I am not able to clear my doubt regarding it in the pointed thread 141 in your last response. I have attached a screenshot from http://docs.graylog.org/en/2.4/pages/collector_sidecar.html for reference on the raised concern. I did not found an explained reference over this official link as well. 
Can you help me in understanding - how Graylog is making sure not to accept logs from any random collector host? OR how it is authorizing the collector host if this feature is already implemented in the Current Graylog version? 

![selection_280](https://user-images.githubusercontent.com/37732255/42769647-6c357288-8940-11e8-9492-123a2cc6f265.png)

**Comment by mariussturm** [comment] 2018-07-17 08:51
@anmolsharmaa in 3.0 there will be token based authentication for the REST requests the Sidecar is doing. How to secure each individual collector that is managed by the Sidecar is out of scope of a Github issue. Please refer the documentation about SSL and certificate based authentication of the collector in question.

**Closed by mariussturm** 2018-07-17 08:51 UTC
